name: damandu
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  go_router:
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  flutter_riverpod: ^2.3.6
  flutter_speed_dial: ^7.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  image: ^3.0.1
  exif: ^2.0.4
  shimmer: ^2.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  kakao_flutter_sdk_user:
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  shared_preferences:
  device_info_plus:
  package_info_plus:
  apple_product_name:
  url_launcher: ^6.1.7
  path_provider: ^2.0.11
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.1.3
  lottie: ^3.3.0
  intl: ^0.20.2
  table_calendar: ^3.1.2
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.11.0
  sign_in_with_apple:
  fl_chart: ^0.68.0
  geolocator: ^10.1.0
  background_locator_2: ^2.0.6


  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.9.4
  google_maps_flutter: ^2.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.3.1
  build_runner: ^2.4.5
  json_serializable: ^6.7.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/image/


  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-ExtraBold.otf

        - asset: fonts/Pretendard-Bold.otf

        - asset: fonts/Pretendard-SemiBold.otf

        - asset: fonts/Pretendard-Medium.otf

        - asset: fonts/Pretendard-Regular.otf

        - asset: fonts/Pretendard-Light.otf

        - asset: fonts/Pretendard-ExtraLight.otf

        - asset: fonts/Pretendard-Thin.otf



    - family: SCDream
      fonts:
        - asset: fonts/SCDream2.otf
          weight: 200
        - asset: fonts/SCDream3.otf
          weight: 300
        - asset: fonts/SCDream4.otf
          weight: 400
        - asset: fonts/SCDream5.otf
          weight: 500
        - asset: fonts/SCDream6.otf
          weight: 600
        - asset: fonts/SCDream7.otf
          weight: 700
        - asset: fonts/SCDream8.otf
          weight: 800
        - asset: fonts/SCDream9.otf
          weight: 900



